Sending-Message-To-Mattermost
vatesfr/xo-server-transport-slack pull request #2
Opened 2016-11-17 14:23 UTC by badrAZ

2016-11-18 10:54 UTC, julien-f commented
@pdonias Could you do a first pass review?

2016-11-18 11:27 UTC, pdonias commented on README.md
> +1. Login in your Slack team account.
"Log in your Slack team account"

2016-11-18 11:31 UTC, pdonias commented on README.md
> +6. Modify the default setting and click on **Save Settings**.
"default settingS"?

2016-11-18 11:33 UTC, pdonias commented on src/index.js
> +      description: 'The bot icone. It can be a slack emoji or an URL image.'
icon*

2016-11-18 11:38 UTC, badrAZ commented on README.md
> +6. Modify the default setting and click on **Save Settings**.
yes, it's default settings i will fix it.

2016-11-18 11:40 UTC, pdonias commented on src/index.js
> +  console.error('[WARN] plugin transport-slack:', error && error.stack || error)
Why `|| error`?

2016-11-18 11:43 UTC, badrAZ commented on src/index.js
> +  console.error('[WARN] plugin transport-slack:', error && error.stack || error)
If the error.stack doesn't exist

2016-11-18 11:44 UTC, julien-f commented on src/index.js
> +      description: 'The bot icone. It can be a slack emoji or an URL image.'
`an URL` → `a URL`.

2016-11-18 11:44 UTC, julien-f commented on src/index.js
> +  console.error('[WARN] plugin transport-slack:', error && error.stack || error)
Because `error` can not have a `stack`.

2016-11-18 15:15 UTC, pdonias commented on README.md
> +3. Search **Incoming WebHooks**
Add an empty line between text and image.

2016-11-18 15:15 UTC, pdonias commented on README.md
> +5. Choose the default channel and click on **Add Incoming WebHooks integration**
Idem.

2016-11-18 15:15 UTC, pdonias commented on README.md
> +6. Modify the default settings and click on **Save Settings**
Idem.

2016-11-18 15:17 UTC, julien-f commented on README.md
> +3. Search **Incoming WebHooks**
You mean between image and text?

Are we sure it won't break the list?

2016-11-18 15:19 UTC, julien-f requested changes

2016-11-18 15:19 UTC, julien-f commented on src/index.js
> +    text
Use `message` instead of `text`.

2016-11-18 15:19 UTC, julien-f commented on src/index.js
> +    this._conf.text = text
Nope, do not store the current message in the configuration.

2016-11-18 15:19 UTC, julien-f commented on src/index.js
> +    return this._send(this._conf).catch(logAndRethrow)
`this._send({ ...this._conf, text: message })`

2016-11-18 15:19 UTC, julien-f commented on src/index.js
> +    this._sendSlack = ::this._sendSlack
Do you understand what this line does?

2016-11-18 15:20 UTC, pdonias commented on README.md
> +3. Search **Incoming WebHooks**
No, between text ("3. Search...") and image (DocImg2.png). Otherwise, the image is on the same line as the text.

2016-11-18 15:21 UTC, julien-f commented on README.md
> +3. Search **Incoming WebHooks**
I see.

2016-11-18 16:20 UTC, badrAZ commented on src/index.js
> +    this._sendSlack = ::this._sendSlack
When we call it, it will have as context this of the class.

2016-11-19 13:38 UTC, julien-f requested changes

2016-11-19 13:38 UTC, julien-f commented on README.md
> +This method is called to test the configuration plugin.
Not necessary to document lifecycle methods, those are standard.

2016-11-19 13:38 UTC, julien-f commented on README.md
> +### `_sendSlack(message) `
Document the exposed method instead: `Xo#sendSlackMessage({ message })`.

2016-11-23 08:37 UTC, julien-f approved these changes

2016-11-23 08:37 UTC, merged